version: '3.4'

services:

  timetracker-db:
    environment:
      POSTGRES_USER: timetracker_user
      POSTGRES_PASSWORD: timetracker_pass
      POSTGRES_DB: timetracker
    volumes:
      - pgdata:/var/lib/postgresql/data

  timetracker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44397
    ports:
      - "10002:80"
      - "44397:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  timetracker-client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=44398
    ports:
      - "12609:80"
