version: '3.4'

services:

  reverse-proxy:
    build:
      context: src/TimeTracker.Proxy
    ports:
      - "5110:80"
      - "5111:5001"
    networks:
      - overlay
    depends_on:
      - timetracker-client

  timetracker-client:
    image: ${DOCKER_REGISTRY-}timetrackerclient
    build:
      context: .
      dockerfile: src/TimeTracker.Client/build/Dockerfile
    networks:
      - overlay
    depends_on:
      - timetracker

  timetracker:
    image: ${DOCKER_REGISTRY-}timetracker
    build:
      context: .
      dockerfile: src/TimeTracker/Dockerfile
    networks:
      - overlay
    depends_on:
      - timetracker-db

  timetracker-db:
    image: postgres:alpine
    networks:
      - overlay

networks:
  overlay:
