version: '3.4'

services:

  timetracker:
    image: ${DOCKER_REGISTRY-}timetracker
    build:
      context: .
      dockerfile: src/TimeTracker/Dockerfile
    networks:
      - overlay

  timetracker-client:
    image: ${DOCKER_REGISTRY-}timetrackerclient
    build:
      context: .
      dockerfile: src/TimeTracker.Client/build/Dockerfile
    networks:
      - overlay
    depends_on:
      - timetracker

  timetracker-db:
    image: postgres:alpine
    networks:
      - overlay

networks:
  overlay:
